### ISSUE TITLE
Aggregation of dynamic list of metrics [question]

### ISSUE THREAD

**Issue by m0zart89** [gnocchixyz/gnocchi#741]
Version: Gnocchi 2.2.1

I have 3 resource types:

1) Default _instance_network_interface_ with metrics _network.incoming.bytes.delta_ and _network.outgoing.bytes.delta_.

2) Default _host_network_interface_ with metrics _hardware.network.incoming.bytes.delta_ and _hardware.network.outgoing.bytes.delta_.

3) Custom _account_ with metrics _incoming.bytes.delta_ and _outgoing.bytes.delta_ (entity from billing).

Supposing that :
1. Customer uses VM1 and SwitchPort2 at the start of the month. 
2. Week later he starts using VM2.
3. Week later he no longer uses SwitchPort2.

So I want total bandwidth for this customer in the end of the month and so I calculate current delta as sum of services every 5 minutes for example.

For this purpose I have relation.yaml:
```yaml
---
- account_id: 839f3f03-5a0d-55a1-a50a-47a2a337b99a #C
  sources:
  - resource_id: 0f1a8f61-0294-56d8-961f-6dd10d6e70d7 #A
    sign: true
  - resource_id: a52a8201-fdab-5910-a82f-10ca1215b917 #B
    sign: true
```
which  I edit every time when customer changes his services in billing.

Is this good way or I can use some existing aggregation methods ?

P.s.: accounts may have one and the same resources ( N to N ).
